# Grunt aliases
---
# Build everything
build:
  - 'build:images'
  - 'build:css'
  - 'build:i18n'
# Build CSS from SCSS to production
'build:css':
  - 'postcss:build'
  - 'rtlcss'
  - 'cssmin'
# Optimise images from source to production
'build:images':
  - 'imagemin'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'
# Check health of the project
check:
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'
# Default task
'artifact':
  - 'shell:composer-install-production'
  # Build like we normally would
  - 'release'
  # Remove build folder
  - 'clean:artifact'
  # Copy only the relevant files to the folder
  - 'copy:artifact'
  # Create a zip file
  - 'compress:artifact'
  - 'restore-environment-after-artifact'

clean:build-assets:
  - 'clean:build-assets-js'
  - 'clean:build-assets-css'

# Update all versions except the stable tag
'update-version-trunk':
  - 'update-version:pluginFile'
  - 'update-version:initializer'

# Get the project ready for release
release:
  - 'build:images'
  - 'clean:build-assets'
  - 'build:css'
  - 'build:i18n'

'deploy:trunk':
  - 'update-version-trunk'
  - 'artifact'
  - 'wp_deploy:trunk'

'deploy:master':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:master'

'restore-environment-after-artifact':
  - 'shell:composer-reset-config'
  - 'shell:composer-reset-lock'
  - 'shell:composer-install-dev'

default:
  - build
