# Grunt aliases
---
# Build everything
build:
  - 'build:images'
  - 'build:css'
  - 'build:i18n'
# Build CSS from SCSS to production
'build:css':
  - 'postcss:build'
  - 'rtlcss'
  - 'cssmin'
# Optimise images from source to production
'build:images':
  - 'imagemin'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'
# Check health of the project
check:
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'
# Default task
default:
  - build
