# Grunt aliases
---
# Build everything
build:
  - 'build:images'
  - 'build:css'
  - 'build:i18n'

# Build CSS from SCSS to production
'build:css':
  - 'clean:build-assets-css'
  - 'sass:build'
  - 'postcss:build'
  - 'rtlcss:build'

# Optimise images from source to production
'build:images':
  - 'imagemin'

# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'

# Check health of the project
check:
  - 'shell:php-lint'
  - 'phpcs'
  - 'checktextdomain'

# Build a distribution zip file
'artifact':
  - 'shell:composer-install-production'
  # Build like we normally would
  - 'release'
  # Remove build folder
  - 'clean:artifact'
  # Copy only the relevant files to the folder
  - 'copy:artifact'
  # Create a zip file
  - 'compress:artifact'
  - 'restore-environment-after-artifact'

# Update all versions except the stable tag
'update-version-trunk':
  - 'update-version:pluginFile'
  - 'update-version:initializer'

# Get the project ready for release
release:
  - 'build:images'
  - 'build:css'
  - 'build:i18n'

# Deploy current state to WordPress.org trunk
'deploy:trunk':
  - 'update-version-trunk'
  - 'artifact'
  - 'wp_deploy:trunk'

# Deploy current state to WordPress.org master
'deploy:master':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:master'

'restore-environment-after-artifact':
  - 'shell:composer-reset-config'
  - 'shell:composer-reset-lock'
  - 'shell:composer-install-dev'

# Default task
default:
  - build
