language: php

sudo: false

php:
- '5.5'

env:
- WP_VERSION=master WP_MULTISITE=0 PHPLINT=1

matrix:
  include:
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.4'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: "5.5"
      env: WP_VERSION=3.9 WP_MULTISITE=1
    - php: "5.3"
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: "5.2"
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1

before_script:
- bin/before.sh

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPLINT" == "1" ]]; then /tmp/wordpress/phpcs/scripts/phpcs -p -s -v -n . --standard=./ruleset.xml --extensions=php; fi
- if [[ "$PHPLINT" == "1" ]]; then if [[ "$WP_MULTISITE" == "0" ]]; then if [[ "$WP_VERSION" == "master" ]]; then composer install --dev; fi fi fi
- if [[ "$PHPLINT" == "1" ]]; then if [[ "$WP_MULTISITE" == "0" ]]; then if [[ "$WP_VERSION" == "master" ]]; then phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; else phpunit -c phpunit.xml; fi fi fi

after_script:
- bin/after.sh